---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  serviceName: "postgresDB"
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      hostname: pg-db
      subdomain: backend
      containers:
      - image: azcontregxpto.azurecr.io/pgdb:latest
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: $POSTGRES_ACC_PSW
        - name: POSTGRES_USER
          value: $POSTGRES_ACC_USR
        - name: PGDATA
          value: $DB_DIR
        - name: POSTGRES_DB
          value: $DB_NAME
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: $MOUNT_PATH
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
  volumeClaimTemplates:
  - metadata:
    name: postgres-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: default
      resources:
        requests:
          storage: 20Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: go-mvc
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: go-mvc
    spec:
      containers:
      - name: gomvc
        image: azcontregxpto.azurecr.io/gomvc:$BUILD_NUMBER
        env:
        - name: DB_HOST
          value: "pg-db.backend.svc.cluster.local:5432"
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: go-mvc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: go-mvc
